#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.templates
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Telephone_Service")]
	public partial class ViewsTemplateDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ViewsTemplateDataContext() : 
				base(global::Templates.Properties.Settings.Default.Telephone_ServiceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ViewsTemplateDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ViewsTemplateDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ViewsTemplateDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ViewsTemplateDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GetCurrentStatus> GetCurrentStatus
		{
			get
			{
				return this.GetTable<GetCurrentStatus>();
			}
		}
		
		public System.Data.Linq.Table<GetActiveIssiue> GetActiveIssiues
		{
			get
			{
				return this.GetTable<GetActiveIssiue>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GetCurrentStatus")]
	public partial class GetCurrentStatus
	{
		
		private int _History_ID;
		
		private int _History_Issiue_ID;
		
		private string _History_From_Status;
		
		private string _History_To_Status;
		
		private System.DateTime _History_Date;
		
		private string _History_Comment;
		
		private int _Issiue_ID;
		
		private int _Issiue_Client_ID;
		
		private int _Issiue_Phone_ID;
		
		private int _Priority;
		
		public GetCurrentStatus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_History_ID", DbType="Int NOT NULL")]
		public int History_ID
		{
			get
			{
				return this._History_ID;
			}
			set
			{
				if ((this._History_ID != value))
				{
					this._History_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_History_Issiue_ID", DbType="Int NOT NULL")]
		public int History_Issiue_ID
		{
			get
			{
				return this._History_Issiue_ID;
			}
			set
			{
				if ((this._History_Issiue_ID != value))
				{
					this._History_Issiue_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_History_From_Status", DbType="NChar(10)")]
		public string History_From_Status
		{
			get
			{
				return this._History_From_Status;
			}
			set
			{
				if ((this._History_From_Status != value))
				{
					this._History_From_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_History_To_Status", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string History_To_Status
		{
			get
			{
				return this._History_To_Status;
			}
			set
			{
				if ((this._History_To_Status != value))
				{
					this._History_To_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_History_Date", DbType="DateTime NOT NULL")]
		public System.DateTime History_Date
		{
			get
			{
				return this._History_Date;
			}
			set
			{
				if ((this._History_Date != value))
				{
					this._History_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_History_Comment", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string History_Comment
		{
			get
			{
				return this._History_Comment;
			}
			set
			{
				if ((this._History_Comment != value))
				{
					this._History_Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issiue_ID", DbType="Int NOT NULL")]
		public int Issiue_ID
		{
			get
			{
				return this._Issiue_ID;
			}
			set
			{
				if ((this._Issiue_ID != value))
				{
					this._Issiue_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issiue_Client_ID", DbType="Int NOT NULL")]
		public int Issiue_Client_ID
		{
			get
			{
				return this._Issiue_Client_ID;
			}
			set
			{
				if ((this._Issiue_Client_ID != value))
				{
					this._Issiue_Client_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issiue_Phone_ID", DbType="Int NOT NULL")]
		public int Issiue_Phone_ID
		{
			get
			{
				return this._Issiue_Phone_ID;
			}
			set
			{
				if ((this._Issiue_Phone_ID != value))
				{
					this._Issiue_Phone_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int NOT NULL")]
		public int Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GetActiveIssiues")]
	public partial class GetActiveIssiue
	{
		
		private int _Issiue_ID;
		
		private int _Issiue_Client_ID;
		
		private int _Issiue_Phone_ID;
		
		private int _Priority;
		
		public GetActiveIssiue()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issiue_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Issiue_ID
		{
			get
			{
				return this._Issiue_ID;
			}
			set
			{
				if ((this._Issiue_ID != value))
				{
					this._Issiue_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issiue_Client_ID", DbType="Int NOT NULL")]
		public int Issiue_Client_ID
		{
			get
			{
				return this._Issiue_Client_ID;
			}
			set
			{
				if ((this._Issiue_Client_ID != value))
				{
					this._Issiue_Client_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issiue_Phone_ID", DbType="Int NOT NULL")]
		public int Issiue_Phone_ID
		{
			get
			{
				return this._Issiue_Phone_ID;
			}
			set
			{
				if ((this._Issiue_Phone_ID != value))
				{
					this._Issiue_Phone_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int NOT NULL")]
		public int Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
